PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE d1_migrations(
		id         INTEGER PRIMARY KEY AUTOINCREMENT,
		name       TEXT UNIQUE,
		applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO "d1_migrations" ("id","name","applied_at") VALUES(1,'0001_create_comments_table.sql','2026-05-19 16:34:01');
CREATE TABLE comments (
    id INTEGER PRIMARY KEY NOT NULL,
    author TEXT NOT NULL,
    content TEXT NOT NULL
);
INSERT INTO "comments" ("id","author","content") VALUES(1,'Kristian','Congrats!');
INSERT INTO "comments" ("id","author","content") VALUES(2,'Serena','Great job!');
INSERT INTO "comments" ("id","author","content") VALUES(3,'Max','Keep up the good work!');
CREATE TABLE tb_emprestimo (   id_emprestimo INTEGER PRIMARY KEY AUTOINCREMENT,   nome TEXT NOT NULL,   email TEXT NOT NULL,   data_reserva TEXT NOT NULL,   unidade TEXT NOT NULL,   nome_produto TEXT,   quant INTEGER,   destinatario TEXT,   processamento INTEGER NOT NULL DEFAULT 0,   unidade_natal TEXT,   unidade_atual varchar(100) not null, data_devolucao date null, data_postagem date null, motivo varchar(500) null, produto_codigo varchar (15) not null, prioridade TEXT CHECK(prioridade IN ('alto', 'intermediário', 'baixo')), aprovacao int default 0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(1,'pato','threeeodivolindos@gmail.com','2026-06-13','SENAI','alicate',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-10 16:51:59','wvsr fbdfb dfbdfr dfb','2311','baixo',1);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(2,'pato','threeeodivolindos@gmail.com','2026-06-06','SENAI','alicate',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-11 13:19:13','t7itim fgjfgjf','2311','baixo',1);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(3,'pato','threeeodivolindos@gmail.com','2026-06-06','SENAI','alicate',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-11 13:19:31','cgjcg gjcjg vbmv','2311','baixo',2);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(4,'pato','threeeodivolindos@gmail.com','2026-06-04','SENAI','Teclado Mecânico USB',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-12 09:11:42','mhg gvjh kjhvjh kjhhjb','TEC-M02','alto',2);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(5,'pato','threeeodivolindos@gmail.com','2026-06-11','SENAI','Teclado Mecânico USB',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-12 09:30:31','dbfsd dfbdf dbsdbs','TEC-M02','baixo',2);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(6,'pato','threeeodivolindos@gmail.com','2026-06-06','SENAI','Teclado Mecânico USB',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-12 09:32:34','adv sdvd sdvsd','TEC-M02','baixo',2);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(7,'pato','threeeodivolindos@gmail.com','2026-06-05','SENAI','Teclado Mecânico USB',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-12 09:36:32','jhvhjg hgvjh kjhvj','TEC-M02','intermediário',2);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(8,'pato','threeeodivolindos@gmail.com','2026-06-05','SENAI','Cadeira de Escritório Ergonômica',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-12 09:36:32','jhvhjg hgvjh kjhvj','CAD-E05','intermediário',2);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(9,'pato','threeeodivolindos@gmail.com','2026-06-05','SENAI','Monitor LED 24 Polegadas',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-12 09:36:32','jhvhjg hgvjh kjhvj','MON-001','intermediário',2);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(10,'pato','threeeodivolindos@gmail.com','2026-06-04','SENAI','Monitor LED 24 Polegadas, Teclado Mecânico USB, Cadeira de Escritório Ergonômica',3,'pato',1,'SENAI','SENAI',NULL,'2026-06-12 09:40:22','dgsrhrh dfnsd gnstdnt','MON-001, TEC-M02, CAD-E05','intermediário',2);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(11,'pato','threeeodivolindos@gmail.com','2026-06-10','SENAI','Monitor LED 24 Polegadas',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-12 09:44:06','ssfbnfn fnsd sdgnsdg','MON-001','baixo',1);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(12,'pato','threeeodivolindos@gmail.com','2026-06-27','SENAI','Monitor LED 24 Polegadas, Teclado Mecânico USB',2,'pato',1,'SENAI','SENAI',NULL,'2026-06-12 09:58:51','gmsrmf','MON-001, TEC-M02','alto',2);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(13,'pato','threeeodivolindos@gmail.com','2026-06-06','SENAI','Monitor LED 24 Polegadas',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-12 10:41:18','stnsfn fgnsn','MON-001','baixo',2);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(14,'user_comum_farr','larissagazoli45@gmail.com','2026-06-30','farroupilha','Monitor LED 24 Polegadas',1,'user_comum_farr',1,'farroupilha','farroupilha',NULL,'2026-06-14 20:27:23','sbjzis svsyia svhs','MON-001','baixo',1);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(15,'admin_gari','gabriel.artuso@aluno.senai.br','2026-06-27','garibaldi','Monitor LED 24 Polegadas',1,'admin_gari',1,'garibaldi','garibaldi',NULL,'2026-06-14 22:47:08','cu','MON-001','alto',1);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(16,'pato','djhdbshsj@mail.co','2026-06-25','SENAI','Monitor LED 24 Polegadas',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-14 22:47:48','sim','MON-001','alto',2);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(17,'pato','threeeodivolindos@gmail.com','2026-06-03','SENAI','Monitor LED 24 Polegadas',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-15 10:16:02','uhbygt ugvytn ytgvbyt','MON-001','baixo',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(18,'lari','threeeodivolindos@gmail.com','2026-06-06','SENAI','Monitor LED 24 Polegadas, Monitor LED 24 Polegadas, Teclado Mecânico USB, Cadeira de Escritório Ergonômica, hsus',5,'lari',1,'SENAI','SENAI',NULL,'2026-06-15 10:18:19','kjhgbgu uybuyb buybuyb','MON-001, MON-001, TEC-M02, CAD-E05, gsusjb','alto',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(19,'lari','threeeodivolindos@gmail.com','2026-06-06','SENAI','Monitor LED 24 Polegadas, Monitor LED 24 Polegadas, Teclado Mecânico USB, Cadeira de Escritório Ergonômica, hsus',5,'lari',1,'SENAI','SENAI',NULL,'2026-06-15 10:18:21','kjhgbgu uybuyb buybuyb','MON-001, MON-001, TEC-M02, CAD-E05, gsusjb','alto',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(20,'threeeo','threeeodivolindos@gmail.com','2026-06-11','SENAI','hsus',1,'threeeo',1,'SENAI','SENAI',NULL,'2026-06-15 10:19:56','uiybutybn ihjbnuyhb uiyhbnuyb','gsusjb','intermediário',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(21,'pato','threeeodivolindos@gmail.com','2026-06-13','SENAI','Monitor LED 24 Polegadas',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-15 10:23:49','ghfcgf jythgfvjtyfhgc kjhfik','MON-001','baixo',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(22,'lari','threeeodivolindos@gmail.com','2026-06-03','SENAI','hsus',1,'lari',1,'SENAI','SENAI',NULL,'2026-06-15 10:24:41','ujyfvtyg jygcdjhg jhkghcyrtcx','gsusjb','baixo',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(23,'lari','threeeodivolindos@gmail.com','2026-06-04','SENAI','Teclado Mecânico USB',1,'lari',1,'SENAI','SENAI',NULL,'2026-06-15 10:33:45','mjndshfvbs sjkeduygfvbsd ksudgf','TEC-M02','baixo',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(24,'lari','threeeodivolindos@gmail.com','2026-06-06','SENAI','Monitor LED 24 Polegadas',1,'lari',1,'SENAI','SENAI',NULL,'2026-06-15 10:39:05','dhmjfb v skdufgsd skudygf skudfgs','MON-001','baixo',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(25,'pato','threeeodivolindos@gmail.com','2026-06-02','SENAI','Monitor LED 24 Polegadas',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-15 10:44:18','hjgv jk,hfg jhgb jhgklhjg','MON-001','baixo',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(26,'lari','threeeodivolindos@gmail.com','2026-06-12','SENAI','Monitor LED 24 Polegadas',1,'lari',1,'SENAI','SENAI',NULL,'2026-06-15 10:46:09','ifvushjdebfv jsdyhvcg jkshdgc sjhdcbvs','MON-001','baixo',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(27,'pato','threeeodivolindos@gmail.com','2026-06-06','SENAI','hsus',1,'pato',1,'SENAI','SENAI',NULL,'2026-06-15 10:47:27','kjadfbhg jsdayhufbgc sjhdgf','gsusjb','baixo',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(28,'threeeo','threeeodivolindos@gmail.com','2026-06-06','SENAI','Cadeira de Escritório Ergonômica',1,'threeeo',1,'SENAI','SENAI',NULL,'2026-06-15 10:47:58','jjhgdbrsfgv jkshdbv sjhdvfb','CAD-E05','baixo',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(29,'user_comum_farr','threeeodivolindos@gmail.com','2026-06-02','farroupilha','Monitor LED 24 Polegadas',1,'user_comum_farr',1,'farroupilha','farroupilha',NULL,'2026-06-15 10:49:04','sjdhbf jsydhgfbv jsydhgf','MON-001','baixo',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(30,'lari','threeeodivolindos@gmail.com','2026-06-11','SENAI','Teclado Mecânico USB',1,'lari',1,'SENAI','SENAI',NULL,'2026-06-15 10:50:59','sdjfhvbsd jsahdfv jsadhgfc','TEC-M02','baixo',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(31,'user_comum_farr','threeeodivolindos@gmail.com','2026-06-06','farroupilha','hsus',1,'user_comum_farr',1,'farroupilha','farroupilha',NULL,'2026-06-15 10:57:05','hfgc  hjgfvxcdjbhwev dghj wgsjahedfvwegjh','gsusjb','baixo',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(32,'user_comum_gari','threeeodivolindos@gmail.com','2026-06-04','garibaldi','Monitor LED 24 Polegadas',1,'user_comum_gari',1,'garibaldi','garibaldi',NULL,'2026-06-15 13:07:24','jsvf shdgvsdjh jsdvcsjdv','MON-001','baixo',1);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(33,'user_comum_gari','threeeodivolindos@gmail.com','2026-06-13','garibaldi','hsus',1,'user_comum_gari',1,'garibaldi','garibaldi',NULL,'2026-06-15 13:10:20','d vsffv sjdgvcsjdhvbsdhj jsdhvbd','gsusjb','baixo',2);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(34,'user_comum_farr','threeeodivolindos@gmail.com','2026-06-06','farroupilha','Cadeira de Escritório Ergonômica',1,'user_comum_farr',1,'farroupilha','farroupilha',NULL,'2026-06-15 13:46:15','fbsdjh smdhvfjhsd jshdvf','CAD-E05','baixo',1);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(35,'user_comum_farr','larissagazoli45@gmail.com','2026-06-25','farroupilha','Cadeira de Escritório Ergonômica',1,'user_comum_farr',1,'farroupilha','farroupilha',NULL,'2026-06-15 14:01:03','hdudd dhid','CAD-E05','baixo',2);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(36,'user_comum_farr','usercomum@gmail.com','2026-06-27','farroupilha','Cadeira de Escritório Ergonômica',1,'user_comum_farr',1,'farroupilha','farroupilha',NULL,'2026-06-15 14:05:35','aldhlw','CAD-E05','alto',0);
INSERT INTO "tb_emprestimo" ("id_emprestimo","nome","email","data_reserva","unidade","nome_produto","quant","destinatario","processamento","unidade_natal","unidade_atual","data_devolucao","data_postagem","motivo","produto_codigo","prioridade","aprovacao") VALUES(37,'user_comum_farr','usercomum@gmail.com','2026-06-26','farroupilha','Monitor LED 24 Polegadas',1,'user_comum_farr',1,'farroupilha','farroupilha',NULL,'2026-06-15 14:06:29','lahslhl','MON-001','baixo',1);
CREATE TABLE tb_estoque (   id_estoque INTEGER PRIMARY KEY AUTOINCREMENT,   nome TEXT NOT NULL,   codigo TEXT NOT NULL,   descricao TEXT NOT NULL,   descricao_detalhada TEXT,   cor TEXT,   quant INTEGER NOT NULL,   uni_intermediarias TEXT,   marca_ref TEXT,   uni_natal TEXT NOT NULL,   pedido TEXT NOT NULL DEFAULT '0',   foto TEXT , uni_atual varchar(150) null, produto_retornado int null default 0);
INSERT INTO "tb_estoque" ("id_estoque","nome","codigo","descricao","descricao_detalhada","cor","quant","uni_intermediarias","marca_ref","uni_natal","pedido","foto","uni_atual","produto_retornado") VALUES(30,'Monitor LED 24 Polegadas','MON-001','Monitor Dell 24" Full HD','Monitor modelo P2419H com ajuste de altura, tela IPS, antirreflexo e conexões HDMI/DisplayPort. Ideal para estações de trabalho.','Preto',15,'TI, Almoxarifado','Dell','Almoxarifado Central','0','img/produtos/mon-001.png','Sala de Treinamento 1',0);
INSERT INTO "tb_estoque" ("id_estoque","nome","codigo","descricao","descricao_detalhada","cor","quant","uni_intermediarias","marca_ref","uni_natal","pedido","foto","uni_atual","produto_retornado") VALUES(31,'Teclado Mecânico USB','TEC-M02','Teclado mecânico switch blue','Teclado mecânico Redragon Kumara com iluminação RGB e switches azuis focados em digitação e durabilidade.','Roxo',30,'TI','Redragon','Almoxarifado Central','0','img/produtos/tec-m02.png','Almoxarifado Central',0);
INSERT INTO "tb_estoque" ("id_estoque","nome","codigo","descricao","descricao_detalhada","cor","quant","uni_intermediarias","marca_ref","uni_natal","pedido","foto","uni_atual","produto_retornado") VALUES(32,'Cadeira de Escritório Ergonômica','CAD-E05','Cadeira presidente com encosto em tela','Cadeira ergonômica com regulagem de altura, encosto para os braços ajustável, suporte lombar e rodízios em silicone.','Preta/Cinza',8,'RH, Compras','Flexform','Depósito Móveis','0','img/produtos/cad-e05.png','Recepção Principal',0);
CREATE TABLE tb_usuarios (   id INTEGER PRIMARY KEY AUTOINCREMENT,   usuario TEXT NOT NULL,   senha TEXT NOT NULL,   nivel_conta INTEGER NOT NULL,   unidade TEXT NOT NULL );
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(1,'lari','12345',0,'SENAI');
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(2,'pato','12345',1,'SENAI');
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(3,'threeeo','t3',3,'SENAI');
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(4,'user_comum_gari','senha123',0,'garibaldi');
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(5,'user_comum_farr','senha123',0,'farroupilha');
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(6,'operador_gari','senha123',1,'garibaldi');
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(7,'operador_farr','senha123',1,'farroupilha');
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(8,'gerente_gari','senha123',2,'garibaldi');
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(9,'gerente_farr','senha123',2,'farroupilha');
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(10,'admin_gari','senha123',3,'garibaldi');
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(11,'admin_farr','senha123',3,'farroupilha');
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(12,'pato_radio','12345',2,'Farroupilha');
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(13,'hhunv','12345',2,'hcdybv');
INSERT INTO "tb_usuarios" ("id","usuario","senha","nivel_conta","unidade") VALUES(14,'eu','eu',3,'Nova Prata');
CREATE TABLE tb_carrinho (
    id_carrinho INTEGER PRIMARY KEY AUTOINCREMENT,
    produto VARCHAR(100) NOT NULL,
    quantidade INTEGER DEFAULT 1,
    usuario VARCHAR(64) NOT NULL,
    carrinho INTEGER DEFAULT 1,
    FOREIGN KEY (produto) REFERENCES tb_estoque(nome) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (usuario) REFERENCES tb_usuarios(usuario) ON UPDATE CASCADE ON DELETE CASCADE
);
INSERT INTO "tb_carrinho" ("id_carrinho","produto","quantidade","usuario","carrinho") VALUES(32,'Monitor LED 24 Polegadas',9,'gerente_farr',1);
INSERT INTO "tb_carrinho" ("id_carrinho","produto","quantidade","usuario","carrinho") VALUES(33,'Monitor LED 24 Polegadas',9,'gerente_farr',1);
INSERT INTO "tb_carrinho" ("id_carrinho","produto","quantidade","usuario","carrinho") VALUES(44,'Monitor LED 24 Polegadas',28,'operador_farr',1);
INSERT INTO "tb_carrinho" ("id_carrinho","produto","quantidade","usuario","carrinho") VALUES(46,'Monitor LED 24 Polegadas',12,'gerente_farr',1);
INSERT INTO "tb_carrinho" ("id_carrinho","produto","quantidade","usuario","carrinho") VALUES(53,'Monitor LED 24 Polegadas',8,'admin_farr',1);
INSERT INTO "tb_carrinho" ("id_carrinho","produto","quantidade","usuario","carrinho") VALUES(99,'Monitor LED 24 Polegadas',1,'user_comum_farr',1);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('d1_migrations',1);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('tb_usuarios',14);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('tb_estoque',35);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('tb_emprestimo',37);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('tb_carrinho',99);
CREATE UNIQUE INDEX idx_usuario_unico ON tb_usuarios(usuario);
CREATE UNIQUE INDEX idx_produto_unico ON tb_estoque(nome);
